# These are supported funding model platforms

github: jaredhanson
patreon: ramisj12
open_collective: # Replace with a single Open Collective username
ko_fi: ramisj12
tidelift: # 
community_bridge: Pro_Medic
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
